name: Build, Test and Deploy React Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci, build and test
        run: |
          npm ci
          npm run jsdoc
          npm run build --if-present
          npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

      - name: authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # --- VÉRIFICATION DE LA VERSION DU PACKAGE ---
      - name: Check package versions
        id: check-version
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          LOCAL_VERSION=$(node -p "require('./package.json').version")

          REMOTE_VERSION=$(npm view $PACKAGE_NAME version 2>/dev/null || echo "0.0.0")

          echo "local_version=$LOCAL_VERSION" >> $GITHUB_OUTPUT
          echo "remote_version=$REMOTE_VERSION" >> $GITHUB_OUTPUT

          echo "Version locale : $LOCAL_VERSION"
          echo "Version distante (NPM) : $REMOTE_VERSION"

      - name: build and publish package on NPM
        # La condition vérifie l'étape précédente pour comparer les versions locale et distante du package. Si elles sont différentes, cela signifie qu'il y a une nouvelle version à publier.
        if: steps.check-version.outputs.local_version != steps.check-version.outputs.remote_version
        run: |
          npm run build-npm-ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build_test

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    permissions:
      pages: write
      id-token: write

    #deploy to github pages
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  build-docker:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Frontend Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/frontend -f DockerfileReact .

      - name: Push Frontend Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/frontend

      - name: Build Backend Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/backend -f DockerfileBackend .

      - name: Push Backend Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/backend
